sudo: required
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
services:
  - docker

before_install:
  - docker build -t cengsili/docker-react .

script:
  - npm test
