sudo: required
services:
  - docker

before_install:
  - docker build -t cengsili/docker-react .

script:
<<<<<<< HEAD
  - docker run cengsili/docker-react npm run test -- --coverage
=======
  - docker run cengsili/docker-react npm run test -- -- coverage

# deploy: 
#   provider: elasticbeanstalk
#   region: "tr"
#   app : docker
>>>>>>> App.test.js
